spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harvanshsaraswat/ECOM.git
          searchPaths: config,config/dev,config/test,config/prod
          cloneOnStart: true

server:
  port: 8765	