spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harvanshsaraswat/ECOM.git
          searchPaths: config
          cloneOnStart: true

server:
  port: 8765	