spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harvanshsaraswat/ECOM
          skipSslValidation: true
          cloneOnStart: true

server:
  port: 8765	